version: "3"

services:
  code-server:
    restart: always
    build: ../image/.
    image: code-server
    container_name: code-server-container
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ".:/home/workspace"
    environment:
      PASSWORD: ibhubs